# -*- coding: utf-8 -*-
"""data_cleaner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14i6zw--yR280k8d7kHjsuQctWkzcgQ8E
"""



import os
import pickle
import numpy as np
import pandas as pd
from scipy.signal import welch
from tqdm import tqdm

SAMPLING_RATE = 128

CHANNELS = {
    "AF3":2,
    "T7":7,
    "Pz":31,
    "T8":25,
    "AF4":19
}

BANDS = {
    "theta":(4,7),
    "alpha":(8,13),
    "low_beta":(14,20),
    "high_beta":(20,30),
    "gamma":(30,45)
}

def bandpower(signal, band, fs):
    fmin, fmax = band
    freqs, psd = welch(signal, fs=fs, nperseg=256)
    idx = np.logical_and(freqs >= fmin, freqs <= fmax)
    return np.mean(psd[idx])

def emotion_class(valence, arousal):

    if valence > 5 and arousal > 5:
        return 0   # excited
    elif valence > 5 and arousal <= 5:
        return 1   # relaxed
    elif valence <= 5 and arousal > 5:
        return 2   # angry
    else:
        return 3   # sad

DATA_PATH = "data_preprocessed_python"  # change if needed

features = []
labels = []

files = sorted(os.listdir(DATA_PATH))

for file in tqdm(files):

    if not file.endswith(".dat"):
        continue

    with open(os.path.join(DATA_PATH, file), "rb") as f:
        subject = pickle.load(f, encoding="latin1")

    data = subject["data"]
    lab = subject["labels"]

    for trial in range(data.shape[0]):

        trial_features = []

        for ch_name, ch_idx in CHANNELS.items():

            signal = data[trial, ch_idx, :]

            for band_name, band_range in BANDS.items():
                power = bandpower(signal, band_range, SAMPLING_RATE)
                trial_features.append(power)

        features.append(trial_features)

        valence = lab[trial,0]
        arousal = lab[trial,1]

        labels.append(emotion_class(valence, arousal))

X = np.array(features)
y = np.array(labels)

print("Feature shape:", X.shape)
print("Label shape:", y.shape)

columns = []

for ch in CHANNELS.keys():
    for band in BANDS.keys():
        columns.append(f"{ch}_{band}")

df = pd.DataFrame(X, columns=columns)
df["label"] = y

df.to_csv("eeg_features_dataset.csv", index=False)

print("Dataset saved!")



